import './globals.css';
import Providers from './providers';

export const metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Netflix</title>
        <link rel="icon" type="image/png" href="/netflix-logo.png" />
      </head>

      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
